### ISSUE TITLE
Feature Request: Clear History

### ISSUE THREAD

**Issue by Valeria-AT** [mauriciogior/open-qrcode#2]
Two possible functions to delete the history:

Single item: Long press on a item and then "delete" (e.g. a pop-up-dialogue)
All items: A wastebin-button e.g. in the right upper corner

P.S.: Scanning and handling is good so far! Nice first release.

**Comment by mauriciogior** [comment]
Thanks for the suggestion @Theobald93, will add for next release due to next week.

**Comment by mauriciogior** [comment]
Included on v1.1.
